# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               ISFA
tagline:             'Integer Sequence Formulas and Applications'
url:                  https://github.com/MathHubInfo/ISFA
baseurl:             'http://MathHubInfo.github.io/ISFA/'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
